define([], function () {
  return {
    PropertyPaneDescription: "Page d'accueil BBI : sources de données, héros, navigation et contenus.",
    SourceGroupName: "Sources de données",
    SiteUrlFieldLabel: "URL du site (vide = site courant)",
    SiteUrlFieldDescription: "Site contenant les listes et les bibliothèques. Les sources absentes utilisent des exemples.",
    NewsListFieldLabel: "Liste des actualités",
    SessionsListFieldLabel: "Liste des sessions",
    TrainersListFieldLabel: "Liste des formateurs référents",
    FormationsListFieldLabel: "Liste des formations",
    DocumentsLibraryFieldLabel: "Bibliothèque des supports publiés",
    GalleryLibraryFieldLabel: "Bibliothèque d'images (galerie médias)",
    MaxItemsFieldLabel: "Éléments affichés par section",

    HeroPageDescription: "Héros plein écran, boutons d'action et navigation de la page.",
    HeroGroupName: "Bandeau héros",
    HeroEyebrowFieldLabel: "Sur-titre (petit texte au-dessus du titre)",
    HeroTitleFieldLabel: "Titre principal (une ligne = un retour à la ligne)",
    HeroTitleFieldDescription: "Le titre s'affiche en très grand sur l'image. Deux lignes maximum pour un rendu optimal.",
    HeroSubtitleFieldLabel: "Accroche / sous-titre",
    HeroImageFieldLabel: "Image de fond (URL)",
    HeroImageFieldDescription: "URL absolue d'une image (SiteAssets ou bibliothèque). Vide = visuel BBI intégré.",
    CtaGroupName: "Boutons d'action",
    PrimaryCtaLabelFieldLabel: "Bouton principal — libellé",
    SecondaryCtaLabelFieldLabel: "Bouton secondaire — libellé",
    CtaUrlFieldLabel: "Lien (URL ou ancre #section)",
    NavGroupName: "Navigation & bandeau",
    NavLinksFieldLabel: "Liens de navigation",
    NavLinksFieldDescription: "Une ligne par lien : Libellé | URL (ou #ancre). Un astérisque final met le lien en avant (rouge).",
    AnnouncementFieldLabel: "Bandeau d'information",
    AnnouncementFieldDescription: "Texte du bandeau bleu nuit en haut de page. Vide = dernière actualité à la une.",

    ContentPageDescription: "Accès rapides, chiffres clés et options d'affichage.",
    QuickLinksGroupName: "Accès rapides",
    QuickLinksFieldLabel: "Tuiles d'accès direct",
    QuickLinksFieldDescription: "Une ligne par tuile : icône | titre | sous-titre | URL",
    KpisFieldLabel: "Chiffres clés (bandeau du héros)",
    KpisFieldDescription: "Une ligne par chiffre : valeur | libellé (4 maximum). Vide = bandeau masqué.",
    OptionsGroupName: "Options d'affichage",
    EnableAnnouncementFieldLabel: "Afficher le bandeau d'information",
    EnableGalleryFieldLabel: "Afficher la galerie médias",
    ShowDataNoticesFieldLabel: "Afficher les indicateurs de données de démonstration",
    LayoutCompactFieldLabel: "Héros compact (sans plein écran)",
    FooterNoteFieldLabel: "Mention du pied de page",

    PageTitle: "BBI Intranet",
    LoadingMessage: "Chargement de votre espace…"
  };
});
