define([], function () {
  return {
    PropertyPaneDescription: "Training sessions schedule: filters by track and delivery mode, registration status, add-to-calendar.",
    SourceGroupName: "Data sources",
    DisplayGroupName: "Display",
    SiteUrlFieldLabel: "Site URL (empty = current site)",
    SiteUrlFieldDescription: "Site hosting the Sessions list. Leave empty for the current site.",
    SessionsListFieldLabel: "Sessions list",
    FormationsListFieldLabel: "Courses list (for the track)",
    DefaultFiliereFieldLabel: "Pre-selected track",
    DefaultFiliereFieldDescription: "Optional: only this track is shown on load.",
    MaxItemsFieldLabel: "Sessions displayed",
    ShowPastFieldLabel: "Also show past sessions",
    ShowDataNoticesFieldLabel: "Show sample-data indicators",

    WebPartTitle: "Sessions & registration",
    Eyebrow: "Training schedule",
    CountSingular: "session shown",
    CountPlural: "sessions shown",
    ListLink: "Open the list",
    CalendarCta: "My Outlook calendar",
    SearchLabel: "Search",
    SearchPlaceholder: "Course, code, city…",
    FiliereLabel: "Track",
    ModalityLabel: "Delivery",
    FilterAll: "All",
    IncludePastLabel: "Include past sessions",
    EmptyStateTitle: "No session scheduled",
    EmptyStateHint: "Adjust the filters, or publish new sessions in the Sessions list.",
    NoDate: "Date to be confirmed",
    ModalityUnknown: "Delivery to be confirmed",
    PastBadge: "Past",
    RegisterCta: "Register",
    ComingSoon: "Coming soon",
    SheetCta: "View course page",
    CalendarLink: "Add to my calendar",
    RegistrationNote: "Registrations are handled by the training team. A question? Write to {url}.",
    SupportLink: "BBI support",
    DemoBanner: "Sample data shown: the sessions list is not created yet, or still empty. Your sessions will replace this schedule automatically as soon as you publish them.",
    LoadingMessage: "Loading the schedule…"
  };
});
