define([], function () {
  return {
    PropertyPaneDescription: "Planning des sessions de formation : filtres par filière et modalité, statut d'inscription, ajout à l'agenda.",
    SourceGroupName: "Sources de données",
    DisplayGroupName: "Affichage",
    SiteUrlFieldLabel: "URL du site (vide = site courant)",
    SiteUrlFieldDescription: "Site contenant la liste « Sessions ». Laisser vide pour le site courant.",
    SessionsListFieldLabel: "Liste des sessions",
    FormationsListFieldLabel: "Liste des formations (pour la filière)",
    DefaultFiliereFieldLabel: "Filière pré-sélectionnée",
    DefaultFiliereFieldDescription: "Optionnel : la page n'affiche que cette filière au chargement.",
    MaxItemsFieldLabel: "Nombre de sessions affichées",
    ShowPastFieldLabel: "Afficher aussi les sessions passées",
    ShowDataNoticesFieldLabel: "Afficher les indicateurs de données de démonstration",

    WebPartTitle: "Sessions & inscriptions",
    Eyebrow: "Planning de formation",
    CountSingular: "session affichée",
    CountPlural: "sessions affichées",
    ListLink: "Ouvrir la liste",
    CalendarCta: "Mon agenda Outlook",
    SearchLabel: "Recherche",
    SearchPlaceholder: "Formation, code, ville…",
    FiliereLabel: "Filière",
    ModalityLabel: "Modalité",
    FilterAll: "Toutes",
    IncludePastLabel: "Inclure les sessions passées",
    EmptyStateTitle: "Aucune session programmée",
    EmptyStateHint: "Ajustez les filtres, ou publiez de nouvelles sessions dans la liste « Sessions ».",
    NoDate: "Date à préciser",
    ModalityUnknown: "Modalité à préciser",
    PastBadge: "Passée",
    RegisterCta: "S'inscrire",
    ComingSoon: "Prochainement",
    SheetCta: "Voir la fiche",
    CalendarLink: "Ajouter à mon agenda",
    RegistrationNote: "Les inscriptions sont traitées par l'équipe pédagogique. Une question ? Écrivez au {url}.",
    SupportLink: "support BBI",
    DemoBanner: "Données de démonstration affichées : la liste « Sessions » n'est pas encore créée, ou elle est vide. Vos sessions remplaceront automatiquement ce planning dès la première publication.",
    LoadingMessage: "Chargement du planning…"
  };
});
